apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.storage.pvName }}
  # PV is cluster-scoped — no namespace needed
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce     # only one pod can write at a time
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # manual binding — ties directly to our PVC
  hostPath:
    path: {{ .Values.storage.hostPath }}   # stores data on worker node disk
