apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.pvcName }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""          # must match PV storageClassName
  resources:
    requests:
      storage: {{ .Values.storage.size }}
